/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type CreateBackupConfiguration struct {
	Provider string `json:"provider,omitempty"`
	Credentials string `json:"credentials,omitempty"`
	Frequency string `json:"frequency,omitempty"`
	Directory string `json:"directory,omitempty"`
	Email string `json:"email,omitempty"`
	Retention string `json:"retention,omitempty"`
	Databases string `json:"databases,omitempty"`
}
