/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Certificate struct {
	Domain        string `json:"domain,omitempty"`
	RequestStatus string `json:"request_status,omitempty"`
	CreatedAt     string `json:"created_at,omitempty"`
	Id            int32  `json:"id,omitempty"`
	Existing      string `json:"existing,omitempty"`
	Active        string `json:"active,omitempty"`
}
