/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type CreateCertificate struct {
	Type_ string `json:"type,omitempty"`
	Domain string `json:"domain,omitempty"`
	Country string `json:"country,omitempty"`
	State string `json:"state,omitempty"`
	City string `json:"city,omitempty"`
	Organization string `json:"organization,omitempty"`
	Department string `json:"department,omitempty"`
}
