/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type SiteIdWorkersBody struct {
	Connection string `json:"connection,omitempty"`
	Timeout string `json:"timeout,omitempty"`
	Sleep string `json:"sleep,omitempty"`
	Tries string `json:"tries,omitempty"`
	Processes string `json:"processes,omitempty"`
	Stopwaitsecs string `json:"stopwaitsecs,omitempty"`
	Daemon string `json:"daemon,omitempty"`
	Force string `json:"force,omitempty"`
	PhpVersion string `json:"php_version,omitempty"`
	Queue string `json:"queue,omitempty"`
}
