/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Job struct {
	Id        int32  `json:"id,omitempty"`
	Command   string `json:"command,omitempty"`
	User      string `json:"user,omitempty"`
	Frequency string `json:"frequency,omitempty"`
	Cron      string `json:"cron,omitempty"`
	Status    string `json:"status,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
