/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type UpdateServer struct {
	Name string `json:"name,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	PrivateIpAddress string `json:"private_ip_address,omitempty"`
	MaxUploadSize string `json:"max_upload_size,omitempty"`
	MaxExecutionTime string `json:"max_execution_time,omitempty"`
	Network string `json:"network,omitempty"`
	Timezone string `json:"timezone,omitempty"`
	Tags string `json:"tags,omitempty"`
}
