/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Server struct {
	Id               int32    `json:"id,omitempty"`
	CredentialId     int32    `json:"credential_id,omitempty"`
	Name             string   `json:"name,omitempty"`
	Size             string   `json:"size,omitempty"`
	Region           string   `json:"region,omitempty"`
	PhpVersion       string   `json:"php_version,omitempty"`
	PhpCliVersion    string   `json:"php_cli_version,omitempty"`
	OpcacheStatus    string   `json:"opcache_status,omitempty"`
	DatabaseType     string   `json:"database_type,omitempty"`
	IpAddress        string   `json:"ip_address,omitempty"`
	PrivateIpAddress string   `json:"private_ip_address,omitempty"`
	BlackfireStatus  string   `json:"blackfire_status,omitempty"`
	PapertrailStatus string   `json:"papertrail_status,omitempty"`
	Revoked          string   `json:"revoked,omitempty"`
	CreatedAt        string   `json:"created_at,omitempty"`
	IsReady          string   `json:"is_ready,omitempty"`
	Network          []int32  `json:"network,omitempty"`
	Tags             []string `json:"tags,omitempty"`
}
