/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Regions struct {
	Ocean2 []string `json:"ocean2,omitempty"`
	Linode []int32  `json:"linode,omitempty"`
	Vultr  []int32  `json:"vultr,omitempty"`
	Aws    []int32  `json:"aws,omitempty"`
}
