/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Site struct {
	Id                 int32    `json:"id,omitempty"`
	Name               string   `json:"name,omitempty"`
	Aliases            []string `json:"aliases,omitempty"`
	Username           string   `json:"username,omitempty"`
	Directory          string   `json:"directory,omitempty"`
	Wildcards          string   `json:"wildcards,omitempty"`
	Status             string   `json:"status,omitempty"`
	Repository         string   `json:"repository,omitempty"`
	RepositoryProvider string   `json:"repository_provider,omitempty"`
	RepositoryBranch   string   `json:"repository_branch,omitempty"`
	RepositoryStatus   string   `json:"repository_status,omitempty"`
	QuickDeploy        string   `json:"quick_deploy,omitempty"`
	ProjectType        string   `json:"project_type,omitempty"`
	App                string   `json:"app,omitempty"`
	AppStatus          string   `json:"app_status,omitempty"`
	SlackChannel       string   `json:"slack_channel,omitempty"`
	TelegramChatId     string   `json:"telegram_chat_id,omitempty"`
	TelegramChatTitle  string   `json:"telegram_chat_title,omitempty"`
	DeploymentUrl      string   `json:"deployment_url,omitempty"`
	CreatedAt          string   `json:"created_at,omitempty"`
	Tags               []int32  `json:"tags,omitempty"`
}
