/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Monitor struct {
	Id int32 `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	Type_ string `json:"type,omitempty"`
	Operator string `json:"operator,omitempty"`
	Threshold int32 `json:"threshold,omitempty"`
	Minutes int32 `json:"minutes,omitempty"`
	State string `json:"state,omitempty"`
	StateChangedAt string `json:"state_changed_at,omitempty"`
}
