/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type InlineResponse200 struct {
	ServerId int32 `json:"server_id,omitempty"`
	RanAs string `json:"ran_as,omitempty"`
	ServerName string `json:"server_name,omitempty"`
	Description string `json:"description,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
