/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Backup struct {
	Id             int32    `json:"id,omitempty"`
	DayOfWeek      string   `json:"day_of_week,omitempty"`
	Time           string   `json:"time,omitempty"`
	Provider       string   `json:"provider,omitempty"`
	ProviderName   string   `json:"provider_name,omitempty"`
	Status         string   `json:"status,omitempty"`
	Databases      []string `json:"databases,omitempty"`
	Backups        []int32  `json:"backups,omitempty"`
	LastBackupTime string   `json:"last_backup_time,omitempty"`
}
