/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Deployment struct {
	Id              int32  `json:"id,omitempty"`
	ServerId        int32  `json:"server_id,omitempty"`
	SiteId          int32  `json:"site_id,omitempty"`
	Type_           int32  `json:"type,omitempty"`
	CommitHash      string `json:"commit_hash,omitempty"`
	CommitAuthor    string `json:"commit_author,omitempty"`
	CommitMessage   string `json:"commit_message,omitempty"`
	StartedAt       string `json:"started_at,omitempty"`
	EndedAt         string `json:"ended_at,omitempty"`
	Status          string `json:"status,omitempty"`
	DisplayableType string `json:"displayable_type,omitempty"`
}
