/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Node struct {
	ServerId int32  `json:"server_id,omitempty"`
	Weight   int32  `json:"weight,omitempty"`
	Down     string `json:"down,omitempty"`
	Backup   string `json:"backup,omitempty"`
	Port     int32  `json:"port,omitempty"`
}
