/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type InlineResponse2001 struct {
	Id int32 `json:"id,omitempty"`
	Version string `json:"version,omitempty"`
	Status string `json:"status,omitempty"`
	DisplayableVersion string `json:"displayable_version,omitempty"`
	BinaryName string `json:"binary_name,omitempty"`
	UsedAsDefault string `json:"used_as_default,omitempty"`
	UsedOnCli string `json:"used_on_cli,omitempty"`
}
