/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type ServerIdFirewallrulesBody struct {
	Name string `json:"name,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	Port string `json:"port,omitempty"`
	Type_ string `json:"type,omitempty"`
}
