/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type ServersBody struct {
	UbuntuVersion string `json:"ubuntu_version,omitempty"`
	Type_ string `json:"type,omitempty"`
	Provider string `json:"provider,omitempty"`
	CredentialId string `json:"credential_id,omitempty"`
	Region string `json:"region,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	PrivateIpAddress string `json:"private_ip_address,omitempty"`
	PhpVersion string `json:"php_version,omitempty"`
	Database string `json:"database,omitempty"`
	Maria string `json:"maria,omitempty"`
	DatabaseType string `json:"database_type,omitempty"`
	Network string `json:"network,omitempty"`
	RecipeId string `json:"recipe_id,omitempty"`
	AwsVpcId string `json:"aws_vpc_id,omitempty"`
	AwsSubnetId string `json:"aws_subnet_id,omitempty"`
	AwsVpcName string `json:"aws_vpc_name,omitempty"`
	HetznerNetworkId string `json:"hetzner_network_id,omitempty"`
	Ocean2VpcUuid string `json:"ocean2_vpc_uuid,omitempty"`
	Ocean2VpcName string `json:"ocean2_vpc_name,omitempty"`
	Vultr2NetworkId string `json:"vultr2_network_id,omitempty"`
	Vultr2NetworkName string `json:"vultr2_network_name,omitempty"`
}
