/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Command struct {
	Id              int32  `json:"id,omitempty"`
	ServerId        int32  `json:"server_id,omitempty"`
	SiteId          int32  `json:"site_id,omitempty"`
	UserId          int32  `json:"user_id,omitempty"`
	EventId         int32  `json:"event_id,omitempty"`
	Command         string `json:"command,omitempty"`
	Status          string `json:"status,omitempty"`
	CreatedAt       string `json:"created_at,omitempty"`
	UpdatedAt       string `json:"updated_at,omitempty"`
	ProfilePhotoUrl string `json:"profile_photo_url,omitempty"`
	UserName        string `json:"user_name,omitempty"`
}
