/*
 * Laravel Forge
 *
 * The Forge API allows you to create and interact with servers and sites on Laravel Forge through a simple REST API.
 *
 * API version: 0.0.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package forge

type Rule struct {
	Id        int32  `json:"id,omitempty"`
	Name      string `json:"name,omitempty"`
	Port      int32  `json:"port,omitempty"`
	Type_     string `json:"type,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	Status    string `json:"status,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
}
